### ISSUE TITLE
Missing shelljs module casts exception when adding platform

### ISSUE THREAD

**Issue by durandt** [siebmanb/rappelle-toi#1]
Hi, 

I'm very new to Cordova (but not to mobile development) and my dator is rather clean from anything yet (very few node modules installed). 
When I tried to add a platform (both iOS or Android), I got the following error message: 

```
$ cordova platform add ios
Adding ios project...
iOS project created with cordova-ios@3.8.0
Unknown target-device preference value: "handheld".
Running command: /Users/user/projects/cordova/rappelle-toi/hooks/after_prepare/01_source_file.js /Users/user/projects/cordova/rappelle-toi
module.js:338
    throw err;
          ^
Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/user/projects/cordova/rappelle-toi/hooks/after_prepare/01_source_file.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
Error: Hook failed with error code 1: /Users/user/projects/cordova/rappelle-toi/hooks/after_prepare/01_source_file.js
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:195:23
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
```

The message disappeared after I installed shelljs

```
$ npm install shelljs
```

Regards,

Thibault D.

**Comment by sebastien-p** [comment]
Hi,

You're totally right, to fix this you have to either remove this hook script (since it's just an example and isn't mandatory here) or install shelljs just like you did.

The main point here is we still have to write some readme file for this repo, I'll try to do it soon, probably this saturday.

Anyway, thanks for your feedback!
